##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

load  File.expand_path("DetectOS.rb")  if File.exists?("DetectOS.rb")

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/ubuntu-bionic64-pbspro"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-pbspro"
    v.memory = "2048"

    v.gui    = false
    v.customize [
      "modifyvm",               :id,
      "--cableconnected1",      "on",
      "--hwvirtex",             "on",
      "--nestedpaging",         "on",
      "--largepages",           "on",
      "--ioapic",               "on",
      "--pae",                  "on",
      "--paravirtprovider",     "kvm",
    ]

    if  DetectOS.windows?
      v.customize [
        "modifyvm",     :id,
        "--uartmode1",  "file",
                "W:/Vagrant/ubuntu-pbspro/vagrant/vagrant-tty.log",
        "--uart1",      "0x3F8",    "4",
      ]
    else
      v.customize [
        "modifyvm",     :id,
        "--uartmode1",  "file",
                "/tmp/vagrant-tty.log",
        "--uart1",      "0x3F8",    "4",
      ]
    end
  end

  config.vm.boot_timeout = 900

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
