##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/ubuntu-bionic64-pbspro"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-pbspro"
    v.memory = "2048"

    v.gui    = false
    v.customize [
      "modifyvm",        :id,
      "--hwvirtex",      "on",
      "--nestedpaging",  "on",
      "--largepages",    "on",
      "--ioapic",        "on",
      "--pae",           "on",
      "--paravirtprovider",  "kvm",
    ]
  end

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
